[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
lib_deps = 
    teckel12/NewPing
    arduino-libraries/LiquidCrystal
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.0